trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '20.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Install Node.js'

  - checkout: self
    displayName: 'Checkout code from GitHub'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build Next.js app'

  - script: |
      npm run export
    displayName: 'Export static site (optional if using static export)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-connection'
      appType: 'webAppLinux'
      appName: 'venkatraman-dev'
      package: '$(System.DefaultWorkingDirectory)'
    displayName: 'Deploy to Azure App Service'
