name: Build and deploy Next.js app to Azure Web App - Venkatraman-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Copy necessary files to release folder
        run: |
          mkdir release
          cp -r .next public package.json next.config.js release/
          cp -r node_modules release/
          if [ -f ecosystem.config.js ]; then cp ecosystem.config.js release/; fi

      - name: Zip artifact
        run: cd release && zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E269490A6AE4426BA2044DFAF792CF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B39D127C07814F4F99552B103D268064 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1AC160210D964DFFA4F0A6D3FF864930 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Venkatraman-dev'
          slot-name: 'Production'
          package: .
